version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: db
    ports:
      - "3313:3306"
    environment:
      # Usually these informations should be stored using secrets
      # For easy handover purpose there kept here
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: Dashboard
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backcoffer
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${MYSQL_ROOT_PASSWORD}",
        ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code/app
    depends_on:
      db:
        condition: service_healthy

    environment:
      MYSQL_DATABASE: Dashboard
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_HOST: db
      MYSQL_PORT: 3306
    networks:
      - backcoffer

  frontend:
    image: node:22.5.1-alpine3.20
    container_name: frontend
    working_dir: /app
    command: ./start.sh
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - backcoffer

networks:
  backcoffer:
    driver: "bridge"

volumes:
  db_data:
