# Generated by Django 5.0.7 on 2024-07-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyinsight',
            name='end_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
