# Generated by Django 5.0.7 on 2024-07-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_energyinsight_end_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyinsight',
            name='published',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
