# Generated by Django 5.0.7 on 2024-07-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_energyinsight_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyinsight',
            name='added',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
