# Generated by Django 5.0.7 on 2024-07-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_energyinsight_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyinsight',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
