# Generated by Django 5.0.7 on 2024-07-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_energyinsight_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyinsight',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
